/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

/**
 *
 * @author Paulina
 */
public class Missions2 extends javax.swing.JFrame {

    /**
     * Creates new form IngresarMision
     */
    public Missions2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBuscarMision = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nombreMisionInfo = new javax.swing.JTextField();
        fechaLanInfo = new javax.swing.JTextField();
        fechaFinInfo = new javax.swing.JTextField();
        costoInfo = new javax.swing.JTextField();
        estadoInfo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        scrollbar1 = new java.awt.Scrollbar();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        scrollPane1 = new java.awt.ScrollPane();
        objetivoInfo = new java.awt.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        scrollPane2 = new java.awt.ScrollPane();
        listaCategorias = new java.awt.List();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        scrollPane4 = new java.awt.ScrollPane();
        scrollPane3 = new java.awt.ScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaObjetivos = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBuscarMision.setBackground(new java.awt.Color(153, 153, 255));
        lblBuscarMision.setForeground(new java.awt.Color(0, 0, 0));
        lblBuscarMision.setText("Mission name");
        lblBuscarMision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblBuscarMisionActionPerformed(evt);
            }
        });
        getContentPane().add(lblBuscarMision, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 370, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, 40));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre Misión");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fecha de lanzamiento");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Fecha de finalización");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Coste misión");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Estado misión");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Objetivo misión");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Categorías");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 120, -1));

        nombreMisionInfo.setEditable(false);
        nombreMisionInfo.setBackground(new java.awt.Color(204, 204, 255));
        nombreMisionInfo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(nombreMisionInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 160, 20));

        fechaLanInfo.setEditable(false);
        fechaLanInfo.setBackground(new java.awt.Color(204, 204, 255));
        fechaLanInfo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(fechaLanInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 160, 20));

        fechaFinInfo.setBackground(new java.awt.Color(204, 204, 255));
        fechaFinInfo.setForeground(new java.awt.Color(255, 255, 255));
        fechaFinInfo.setEnabled(false);
        getContentPane().add(fechaFinInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 160, 20));

        costoInfo.setEditable(false);
        costoInfo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(costoInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 170, -1));

        estadoInfo.setEditable(false);
        estadoInfo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(estadoInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 170, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Personal");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));
        getContentPane().add(scrollbar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, -2, -1, 610));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Especializacion");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Entidades afiliadas");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        scrollPane1.add(objetivoInfo);

        getContentPane().add(scrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 180, 30));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 300, 30));

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 620, 90));

        scrollPane2.add(listaCategorias);

        getContentPane().add(scrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 160, 30));

        jTable2.setBackground(new java.awt.Color(204, 204, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 620, 90));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whiteBack (2).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 470));
        getContentPane().add(scrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 620, -1));
        getContentPane().add(scrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 620, 90));

        listaObjetivos.setBackground(new java.awt.Color(255, 255, 255));
        listaObjetivos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(listaObjetivos);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 240, 20));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Objetivos");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 150, -1));

        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/right arrow.jpg"))); // NOI18N
        btnIngresar.setText("jButton2");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, 70, 40));

        jLabel13.setText("Ingresa una mision o actualiza una ya existente ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBuscarMisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblBuscarMisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBuscarMisionActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        IngresarMision ingMision = new IngresarMision();
        ingMision.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Missions2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Missions2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Missions2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Missions2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Missions2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JTextField costoInfo;
    private javax.swing.JTextField estadoInfo;
    private javax.swing.JTextField fechaFinInfo;
    private javax.swing.JTextField fechaLanInfo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField lblBuscarMision;
    private java.awt.List listaCategorias;
    private javax.swing.JList<String> listaObjetivos;
    private javax.swing.JTextField nombreMisionInfo;
    private java.awt.TextField objetivoInfo;
    private java.awt.ScrollPane scrollPane1;
    private java.awt.ScrollPane scrollPane2;
    private java.awt.ScrollPane scrollPane3;
    private java.awt.ScrollPane scrollPane4;
    private java.awt.Scrollbar scrollbar1;
    // End of variables declaration//GEN-END:variables
}
