/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;
import javax.swing.JTable;
import javax.swing.table.*;


/**
 *
 * @author Paulina
 */

public class Observation extends javax.swing.JFrame {
    
    
    
    

    /**
     * Creates new form Observation
     */
    public Observation() {
        initComponents();
        this.setLocationRelativeTo(null);
        Object prueba [][] = {
            {"hola", "adio", "otro"},
            {"fuego","hielo", "mas"}             
        };
        tablaObservaciones.getModel().setValueAt("hola", 0, 0);
        tablaObservaciones.getModel().setValueAt("hola", 1, 0);
        tablaObservaciones.getModel().setValueAt("hola", 0, 1);
        
        
        
        
       
        
        tablaObservaciones.getColumn("Title 1").setHeaderValue("Nombre");
        tablaObservaciones.getColumn("Title 2").setHeaderValue("Objeto");
        tablaObservaciones.getColumn("Title 3").setHeaderValue("Lugar");
        tablaObservaciones.getColumn("Title 4").setHeaderValue("Hora (Zona horaria nacional)");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaObservaciones = new javax.swing.JTable();
        btnRegistrarenObser = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(4, 49, 79));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 204));

        tablaObservaciones.setBackground(new java.awt.Color(255, 255, 255));
        tablaObservaciones.setForeground(new java.awt.Color(0, 0, 0));
        tablaObservaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaObservaciones.setEnabled(false);
        jScrollPane2.setViewportView(tablaObservaciones);

        jScrollPane1.setViewportView(jScrollPane2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 510, 170));

        btnRegistrarenObser.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrarenObser.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarenObser.setText("Registrar");
        btnRegistrarenObser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarenObserActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarenObser, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 90, 30));

        jLabel2.setBackground(new java.awt.Color(204, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registra tus observaciones");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 510, 50));

        jLabel1.setBackground(new java.awt.Color(25, 3, 62));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blueBack (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 650, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarenObserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarenObserActionPerformed
        // TODO add your handling code here:
        RegistrarObservacion rgObservacion = new RegistrarObservacion();
        rgObservacion.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegistrarenObserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Observation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Observation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Observation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Observation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Observation().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarenObser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaObservaciones;
    // End of variables declaration//GEN-END:variables
}
