/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

/**
 *
 * @author Paulina
 */
public class RegistrarObservacion extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarObservacion
     */
    public RegistrarObservacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombreObservacion = new javax.swing.JTextField();
        objetoObservacion = new javax.swing.JTextField();
        lugarObservacion = new javax.swing.JTextField();
        horaObservacion = new javax.swing.JTextField();
        btnRegistrarenObservacion = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingresar registro");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        jLabel4.setText("Objeto");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabel5.setText("Lugar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        jLabel6.setText("Hora");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        nombreObservacion.setBackground(new java.awt.Color(153, 153, 153));
        nombreObservacion.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(nombreObservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 190, -1));

        objetoObservacion.setBackground(new java.awt.Color(153, 153, 153));
        objetoObservacion.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(objetoObservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 190, -1));

        lugarObservacion.setBackground(new java.awt.Color(153, 153, 153));
        lugarObservacion.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lugarObservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 190, -1));

        horaObservacion.setBackground(new java.awt.Color(153, 153, 153));
        horaObservacion.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(horaObservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 190, -1));

        btnRegistrarenObservacion.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrarenObservacion.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarenObservacion.setText("Ingresar");
        getContentPane().add(btnRegistrarenObservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 80, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left arrow.jpg"))); // NOI18N
        btnBack.setText("jButton1");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BlackHole (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        Observation obs = new Observation();
        obs.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarObservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarObservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarObservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarObservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarObservacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegistrarenObservacion;
    private javax.swing.JTextField horaObservacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField lugarObservacion;
    private javax.swing.JTextField nombreObservacion;
    private javax.swing.JTextField objetoObservacion;
    // End of variables declaration//GEN-END:variables
}
